server:
    port: 8076
    
    
spring:
    # 如果是测试环境则dev_model=true 不做验证码校验
    dev_model: true
    
    session:
      store-type: redis
      
    datasource:
      readSize: 1
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      write:
        url: jdbc:mysql://127.0.0.1:3306/mc_user?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: select 'x'

      read:
        url: jdbc:mysql://127.0.0.1:3306/mc_user?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: select 'x'

    redis:
        database: 11
        host: 192.168.1.140
        password:
        port: 6379

#指定log的配置文件，以及记录Spring Boot的log级别  
logging:
    config: classpath:logback.xml     